# Generated by Django 3.0.8 on 2021-01-14 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_better_admin_arrayfield.models.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('small', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), size=2)),
                ('middle', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), size=2)),
                ('large', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), size=2)),
            ],
        ),
        migrations.CreateModel(
            name='PetOwner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, default=' ', max_length=200)),
                ('email', models.EmailField(blank=True, default=' ', max_length=254)),
                ('address', models.CharField(blank=True, default=' ', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_img', models.ImageField(default='poppy/img/profile_img/profile_default.png', upload_to='')),
                ('room_img', models.ImageField(default='poppy/img/room_img/room_default.png', upload_to='')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=2000)),
                ('available_days', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.DateField(blank=True, null=True), size=None)),
                ('available_services', multiselectfield.db.fields.MultiSelectField(choices=[('장기 예약', '장기 예약'), ('실내 놀이', '실내 놀이'), ('약물 복용', '약물 복용'), ('목욕 가능', '목욕 가능'), ('산책 가능', '산책 가능'), ('집앞 픽업', '집앞 픽업')], max_length=35)),
                ('certificates', django_better_admin_arrayfield.models.fields.ArrayField(base_field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=200), size=3), blank=True, default=list, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_img', models.ImageField(default='poppy/img/pet_img/pet_default.png', upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('character', models.CharField(max_length=1000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.FloatField(default=5.0)),
                ('num_of_comments', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_as_author', to=settings.AUTH_USER_MODEL)),
                ('target_petsitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_as_target_petsitter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ongoing', models.BooleanField(default=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('phonenum_of_sender', models.CharField(max_length=11)),
                ('pet_breed', models.CharField(max_length=100)),
                ('pet_size', models.CharField(choices=[('소형견', '소형견'), ('중형견', '중형견'), ('중형견', '대형견')], max_length=10)),
                ('total_fee', models.IntegerField()),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_as_sender', to=settings.AUTH_USER_MODEL)),
                ('target_petsitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_as_petsitter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
