# Generated by Django 3.0.8 on 2021-01-10 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_better_admin_arrayfield.models.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(default='img/profile_img/profile_default.png', upload_to='img/profile_img')),
                ('room_img', models.ImageField(default='img/room_img/room_default.png', upload_to='img/room_img')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=2000)),
                ('available_days', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.DateField(blank=True, null=True), size=None)),
                ('available_services', multiselectfield.db.fields.MultiSelectField(choices=[(0, '오래 맡겨주세요'), (1, '놀이 가능해요'), (2, '약 먹일 수 있어요'), (3, '목욕 가능해요'), (4, '산책 가능해요'), (5, '픽업 해드려요')], max_length=11)),
                ('certificate', django_better_admin_arrayfield.models.fields.ArrayField(base_field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=200), size=2), blank=True, default=list, null=True, size=None)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PetOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('e_mail', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_img', models.ImageField(default='img/pet_img/pet_default.png', upload_to='img/pet_img')),
                ('name', models.CharField(max_length=200)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('character', models.CharField(max_length=1000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), size=2)),
                ('middle', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), size=2)),
                ('large', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), size=2)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.FloatField(default=5.0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_as_author', to=settings.AUTH_USER_MODEL)),
                ('target_petsitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_as_target_petsitter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ongoing', models.BooleanField(default=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('phonenum_of_sender', models.BigIntegerField()),
                ('pet_breed', models.CharField(max_length=100)),
                ('pet_size', models.CharField(choices=[('소형견', '소형견'), ('중형견', '중형견'), ('중형견', '대형견')], max_length=10)),
                ('total_fee', models.IntegerField()),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_as_sender', to=settings.AUTH_USER_MODEL)),
                ('target_petsitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_as_target_petsitter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
