# Generated by Django 3.0.8 on 2021-01-09 10:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poppy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petowner',
            name='certificate',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
