# Generated by Django 3.0.8 on 2021-01-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poppy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petowner',
            name='address',
            field=models.CharField(blank=True, default='서울시', max_length=200),
        ),
    ]
