# Generated by Django 3.0.8 on 2021-01-14 09:00

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('poppy', '0002_auto_20210114_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='small',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(default=30000), size=2),
        ),
    ]
