# Generated by Django 3.0.8 on 2021-01-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poppy', '0002_auto_20210112_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='num_of_comment',
            field=models.IntegerField(default=0),
        ),
    ]
