# Generated by Django 3.0.8 on 2021-01-09 10:42

from django.db import migrations
import jsonfield.fields
import poppy.models


class Migration(migrations.Migration):

    dependencies = [
        ('poppy', '0002_auto_20210109_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petowner',
            name='available_services',
            field=jsonfield.fields.JSONField(default=poppy.models.default_available_services, dump_kwargs={'ensure_ascii': False}),
        ),
        migrations.AlterField(
            model_name='petowner',
            name='certificate',
            field=jsonfield.fields.JSONField(default=dict, dump_kwargs={'ensure_ascii': False}),
        ),
    ]
