# Generated by Django 3.0.8 on 2021-01-09 10:59

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import poppy.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poppy', '0003_auto_20210109_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='poppy.PetOwner')),
                ('profile_img', models.ImageField(default='img/profile_img/profile_default.png', upload_to='img/profile_img')),
                ('room_img', models.ImageField(default='img/room_img/room_default.png', upload_to='img/room_img')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=2000)),
                ('available_days', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(null=True), size=None)),
                ('available_services', jsonfield.fields.JSONField(default=poppy.models.default_available_services, dump_kwargs={'ensure_ascii': False})),
                ('certificate', jsonfield.fields.JSONField(default=dict, dump_kwargs={'ensure_ascii': False})),
            ],
        ),
        migrations.RemoveField(
            model_name='petowner',
            name='available_days',
        ),
        migrations.RemoveField(
            model_name='petowner',
            name='available_services',
        ),
        migrations.RemoveField(
            model_name='petowner',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='petowner',
            name='content',
        ),
        migrations.RemoveField(
            model_name='petowner',
            name='profile_img',
        ),
        migrations.RemoveField(
            model_name='petowner',
            name='room_img',
        ),
        migrations.RemoveField(
            model_name='petowner',
            name='title',
        ),
        migrations.AlterField(
            model_name='petowner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
