# Generated by Django 3.0.8 on 2021-01-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poppy', '0003_auto_20210114_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_img',
            field=models.ImageField(default='pet_img/default_pet.png', upload_to='pet_img'),
        ),
        migrations.AlterField(
            model_name='post',
            name='profile_img',
            field=models.ImageField(default='profile_img/default_profile.png', upload_to='profile_img'),
        ),
        migrations.AlterField(
            model_name='post',
            name='room_img',
            field=models.ImageField(default='room_img/default_room.png', upload_to='room_img'),
        ),
    ]
