# Generated by Django 3.0.8 on 2021-01-12 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poppy', '0003_comment_num_of_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='num_of_comment',
            new_name='num_of_comments',
        ),
    ]
