# Generated by Django 3.0.8 on 2021-01-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poppy', '0004_auto_20210114_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petowner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
