# Generated by Django 3.0.8 on 2021-01-12 05:30

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('poppy', '0004_auto_20210112_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='certificate',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=200), size=3), blank=True, default=list, null=True, size=None),
        ),
    ]
