# Generated by Django 3.0.8 on 2021-01-09 11:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poppy', '0005_auto_20210109_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='small',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=2),
        ),
    ]
