# Generated by Django 3.0.8 on 2021-01-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poppy', '0005_auto_20210112_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_img',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='profile_img',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='room_img',
            field=models.URLField(max_length=300),
        ),
    ]
