# Generated by Django 3.0.8 on 2021-01-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poppy', '0006_auto_20210112_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
