# Generated by Django 3.0.8 on 2021-01-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poppy', '0006_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_img',
            field=models.ImageField(default='https://poppy-mvp.s3.ap-northeast-2.amazonaws.com/pet_img/default_pet.png', upload_to='https://poppy-mvp.s3.ap-northeast-2.amazonaws.com/pet_img'),
        ),
        migrations.AlterField(
            model_name='post',
            name='profile_img',
            field=models.ImageField(default='https://poppy-mvp.s3.ap-northeast-2.amazonaws.com/profile_img/default_profile.png', upload_to='https://poppy-mvp.s3.ap-northeast-2.amazonaws.com/profile_img'),
        ),
        migrations.AlterField(
            model_name='post',
            name='room_img',
            field=models.ImageField(default='https://poppy-mvp.s3.ap-northeast-2.amazonaws.com/room_img/default_room.png', upload_to='https://poppy-mvp.s3.ap-northeast-2.amazonaws.com/room_img'),
        ),
    ]
