# Generated by Django 3.0.8 on 2021-01-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poppy', '0007_application_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='phonenum_of_sender',
            field=models.CharField(max_length=11),
        ),
    ]
