# Generated by Django 3.0.8 on 2021-01-09 13:53

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('poppy', '0007_auto_20210109_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petowner',
            name='is_expert',
        ),
        migrations.AlterField(
            model_name='fee',
            name='large',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(default=0), size=2),
        ),
        migrations.AlterField(
            model_name='fee',
            name='middle',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(default=0), size=2),
        ),
        migrations.AlterField(
            model_name='fee',
            name='small',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(default=0), size=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='available_days',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.DateField(null=True), size=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='available_services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('오래 맡겨주세요', '오래 맡겨주세요'), ('놀이 가능해요', '놀이 가능해요'), ('약 먹일 수 있어요', '약 먹일 수 있어요'), ('목욕 가능해요', '목욕 가능해요'), ('산책 가능해요', '산책 가능해요'), ('픽업 해드려요', '픽업 해드려요')], max_length=51),
        ),
    ]
