# Generated by Django 3.0.8 on 2021-01-09 15:12

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('poppy', '0008_auto_20210109_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='large',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), size=2),
        ),
        migrations.AlterField(
            model_name='fee',
            name='middle',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), size=2),
        ),
        migrations.AlterField(
            model_name='fee',
            name='small',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), size=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='available_services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, '오래 맡겨주세요'), (1, '놀이 가능해요'), (2, '약 먹일 수 있어요'), (3, '목욕 가능해요'), (4, '산책 가능해요'), (5, '픽업 해드려요')], max_length=11),
        ),
    ]
