# Generated by Django 3.0.8 on 2021-01-09 15:22

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('poppy', '0009_auto_20210109_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='small',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8), size=8),
        ),
    ]
