# Generated by Django 3.0.8 on 2021-01-09 15:27

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('poppy', '0010_auto_20210109_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='large',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), default=list, size=2),
        ),
        migrations.AlterField(
            model_name='fee',
            name='middle',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), default=list, size=2),
        ),
        migrations.AlterField(
            model_name='fee',
            name='small',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), default=list, size=2),
        ),
    ]
