# Generated by Django 3.0.8 on 2021-01-09 15:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poppy', '0012_auto_20210109_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='large',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2),
        ),
        migrations.AlterField(
            model_name='fee',
            name='middle',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2),
        ),
        migrations.AlterField(
            model_name='fee',
            name='small',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='available_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(null=True), size=None),
        ),
    ]
