# Generated by Django 3.0.8 on 2021-01-09 17:38

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('poppy', '0014_auto_20210109_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='certificate',
            field=jsonfield.fields.JSONField(default=dict, dump_kwargs={'ensure_ascii': False}, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
