# Generated by Django 3.0.8 on 2021-01-09 19:15

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('poppy', '0015_auto_20210109_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='certificate',
            field=jsonfield.fields.JSONField(blank=True, default=dict, dump_kwargs={'ensure_ascii': False}, null=True),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ongoing', models.BooleanField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('reservation_num', models.IntegerField()),
                ('pet_name', models.CharField(max_length=200)),
                ('pet_size', models.CharField(choices=[(0, '소형견'), (1, '중형견'), (2, '대형견')], max_length=10)),
                ('total_fee', models.IntegerField()),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_as_sender', to='poppy.PetOwner')),
                ('target_petsitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_as_receiver', to='poppy.PetOwner')),
            ],
        ),
    ]
