# Generated by Django 3.0.8 on 2021-01-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poppy', '0016_auto_20210109_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='is_ongoing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='reservation_num',
            field=models.BigIntegerField(),
        ),
    ]
