# Generated by Django 3.0.8 on 2021-01-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poppy', '0017_auto_20210109_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='target_person',
            new_name='target_petsitter',
        ),
        migrations.AlterField(
            model_name='application',
            name='pet_size',
            field=models.CharField(choices=[('소형견', '소형견'), ('중형견', '중형견'), ('중형견', '대형견')], max_length=10),
        ),
    ]
