# Generated by Django 3.0.8 on 2021-01-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poppy', '0018_auto_20210109_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='reservation_num',
            new_name='phonenum_of_sender',
        ),
        migrations.AddField(
            model_name='application',
            name='pet_breed',
            field=models.CharField(default='말티즈', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='pet_name',
            field=models.CharField(max_length=100),
        ),
    ]
